### ISSUE TITLE
Interaction between AmplitudeView and TraceView

### ISSUE THREAD

**Issue by yger** [kwikteam/phy-contrib#97] opened 2017-02-21 10:43 UTC
This is also a thought we had a while ago, but could we clik on an amplitude, and have the TraceView automatically centered, in time, around the corresponding spike? Thanks again for everything!

**Comment by rossant** [comment] 2019-06-14 10:00
duplicate of https://github.com/cortex-lab/phy/issues/840

**Closed by rossant** 2019-06-14 10:00 UTC
Labels: feature
